version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB:       ${DBNAME}
      POSTGRES_USER:     ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  migrations:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
      - migrations
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: